name: default_git_branch
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  git: ^1.1.0
  path: ^1.7.0
  io: ^0.3.4

dev_dependencies:
  pedantic: ^1.9.0

executables:
  default_git_branch:
