name: default_git_branch
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  git: ^2.0.0
  path: ^1.7.0
  io: ^1.0.0

dev_dependencies:
  lints: ^2.0.0

executables:
  default_git_branch:
